### ISSUE TITLE
docs: certificates and environment variables in testing section

### ISSUE THREAD

**Issue by tonyaldon** [Blockstream/greenlight#167]
It seems that there is a mismatch with environment variables in the docs (Testing with `gl-testing`).

At some point we can read `These must match the lines printed above` and the lines seem not to match.

The random element doesn't match: first we have `tmpfo6c2ye2` then we use `tmpb7711nx5`.

And I don't know if we should use `nobody.crt` or `nobody.pem`.  By reading the method `new` of the class `Clients` (in `libs/gl-testing/gltesting/clients.py` file), it seems that it should be `nobody.crt`.  But I'm no sure. 

Here are the parts I'm refering to:

    def test_my_network(clients, node_factory, scheduler, directory, bitcoind):
        ...
        print(f"CA Cert:     {directory}/certs/ca.pem")  # (4)
        print(f"Nobody Cert: {directory}/certs/users/nobody.pem")
        print(f"Nobody Key:  {directory}/certs/users/nobody-key.pem")
        ...

    ...      

    $ pytest testy.py -s
    ...
    CA Cert:     /tmp/gltesting/tmpfo6c2ye2/certs/ca.pem
    Nobody Cert: /tmp/gltesting/tmpfo6c2ye2/certs/users/nobody.pem
    Nobody Key:  /tmp/gltesting/tmpfo6c2ye2/certs/users/nobody-key.pem
    ...

    ...

    export GL_NOBODY_CERT=/tmp/gltesting/tmpb7711nx5/certs/users/nobody.crt
    export GL_NOBODY_KEY=/tmp/gltesting/tmpb7711nx5/certs/users/nobody-key.pem
    export GL_CA_CRT=/tmp/gltesting/tmpb7711nx5/certs/ca.pem
    
    export GL_SCHEDULER_GRPC_URI=http://127.0.0.1:43841

**Comment by nepet** [comment]
Hey Tony,
Thanks for scanning the docs! These directories names are randomly set by `pytest` and should be different on each run, but the same on printing and exporting the env vars. We should fix this in the docs.

You are right assuming that it should be the `nobody.crt` for the `GL_NOBODY_CERT`. The difference is, that the `nobody.crt` includes the whole certificate chain from the certificate authority (CA) to the nobody-user certificate, while the `nobody.pem` is the sole nobody-user cert.

Let me add a little bit to the docs to make this more clear.

What do you think, shall we add an example on how to register a client and fetch a `getinfo` against the mock-network that was created before, to give a litte more direction?

**Comment by tonyaldon** [comment]
Hey nepet,

> What do you think, shall we add an example on how to register a client and fetch a getinfo against the mock-network that was created before, to give a litte more direction?

It would be great and helpful.

Maybe also producing an `invoice` against the mock-network as this requires to pass arguments.
