### ISSUE TITLE
Adding github link to the greenlight page on blockstream website.

### ISSUE THREAD

**Issue by plimdim** [Blockstream/greenlight#172]
I think having a link to github in here https://blockstream.com/lightning/greenlight/ would be nice. 
The link is the documentation. 
But would be more appealing in website since it shows immediately that is opensource.

**Comment by cdecker** [comment]
Thanks for pointing this one out, it took a bit longer, but the Repo is now linked alongside the docs: https://blockstream.com/lightning/greenlight/

**Comment by plimdim** [comment]
Thanks.
