### ISSUE TITLE
glcli with stuck commands: ctrl+c does nothing

### ISSUE THREAD

**Issue by Schnitzel** [Blockstream/greenlight#205]
when pressing `ctrl+c` in a glicli command that is stuck, nothing happens. I need to use `kill [pid]` to actually `glcli`

**Comment by cdecker** [comment]
I'm assuming this is the `glcli hsmd` command. That command runs fully in the rust code, and is thus a bit tricky to reach with signals produced in the python code. There is a shutdown handle on the Rust signer library that we should be able to bind to a signal handler in python.
