### ISSUE TITLE
Signer run_forever hang at some point

### ISSUE THREAD

**Issue by roeierez** [Blockstream/greenlight#209]
Stops to reproduce:
1. Run signer run_forever in one process.
2. schedule the node
3. At this point I am just closing my laptop :) for several hours, I am guessing this can be also disconnecting from the internet for some time.
4. schedule the node again and try a request that requires signing, such as connect to peer.

Expected:
Signer awake and start signing requests, schedule pass succesfully.

Actual:
connect to peer hangs indicating signer is not connected.

**Comment by cdecker** [comment]
My intuition of what is happening here:

 1. The signer calls `Scheduler.get_node_info()` with `wait=true` causing the scheduler to hold on to the connection until the node gets scheduled (long polling)
 2. The node gets scheduled, the signer connects, and opens a stream
 3. The laptop then goes to suspend, causing clocks to stop ticking
 4. The node notices via keepalive that the connection is closed and closes
 5. The node gets preempted causing the connection to terminate (or node notices the signer isn't responding to keepalive messages)
 6. The signer awakes again, unaware that the connection was terminated
 7. The signer waits until its next keepalive expires, or it attempts to send something over the connection, thus noticing that the connection isn't there (node sends an `RST` packet).

Notice that the last step may take several minutes to notice, if keepalives are enabled at all (need to check).

Alternatively the slot has already been reused for another node, thus the mTLS certificates no longer match up, and the signer fails to reconnect after noticing it got disconnected, resulting in spurious TLS handshake errors (`BadCertficate` and friends).

We could shorten the keepalive interval, or we can introduce application layer pings from the signer to the node to reduce the time until the signer notices, but it's a balance between bandwidth usage and dead air, so we need to get this right for mobile users. Better would be the client can be aware of the power state of the device it is running on, and be told that there was a suspend and that it should perform a quick ping once to kill the connection if it didn't survive the suspension (yes, connections may be able to survive short suspends of up to 5 minutes if no keepalives are sent while the endpoint is sleeping...).

**Comment by roeierez** [comment]
Makes sense. Just keep in mind that the signer doesn't recover forever which indicates that gRPC channel keep alive is not configured.
Also from my tests signer doesn't respond to shutdown request at this point so there is not way to restart it.

What do you think of starting with some reasonable keep alive? 5 minutes sounds reasonable to me comparing to not at all and it will allow the signer to recover after long time suspension by the mobile OS.
I can provide feedback on that and if necessary we can afterwards move on to give the application layer more control of detecting liveness and restart the signer.
