### ISSUE TITLE
Drop support for python3.7 in gl-client-py

### ISSUE THREAD

**Issue by ErikDeSmedt** [Blockstream/greenlight#216]
The `glclient` package is currently not functional when used with `python3.7`.
The `SupportsIndex` type was introduced python 3.8 and we use it [here](https://github.com/Blockstream/greenlight/blob/99424f36073433803bfafe33c7920e3568c3b9a7/libs/gl-client-py/glclient/__init__.py#L10C53-L10C66).

I don't think we should support python versions that are end-of-life [end-of-life](https://devguide.python.org/versions/).
Therefore, I suggest we move to 3.9

**Comment by cdecker** [comment]
Addressed by #218
