### ISSUE TITLE
glcli: Stop hsmd on `SIGINT`

### ISSUE THREAD

**Issue by nepet** [Blockstream/greenlight#254]
When starting the hsmd via `glcli hsmd` it is not possible to quit the signer with a `ctrl-c` from the command line (produces a `SIGINT`). It is however possible to kill the process with a `SIGTERM` and to stop it via `ctrl-\` which sends a `SIGQUIT`.

So while we have signals to stop and quit the signer, it seems more convenient to use `ctrl-c` to stop a running process from tty.

**Comment by Randy808** [comment]
Fixed by #278
