### ISSUE TITLE
vls: `policy-routing-balanced` failure

### ISSUE THREAD

**Issue by cdecker** [Blockstream/greenlight#274]
Some users reported an issue paying an invoice with the following error:

```
[2023-09-20T08:17:22Z WARN  lightning_signer::policy] policy failed: policy-routing-balanced validate_payment_balance: incoming_msat + max_to_invoice_msat < outgoing_msat: 0 + 0 < 2498000
```

This happens when processing the following `ValidateCommitmentTx` request:

```
0023000000df020000000191fcb6f06b5b94586b13101b827bb204d78137d87031a346b27501280b239f0d0000000000539ca180044a0100000000000022002096516bcdab4c23f3fa72953bd7214d1fed2c5b537462593b5e5af212d9c96ea34a01000000000000220020d5d031569d1d9b2697f4e6c58064cae906570a0ca246592abb644b1e070fb28ec309000000000000220020a47089358f15df307dc9fbe6105e8bbaed6f5ec9033307992c5b92f83f75b0b18d7f010000000000220020586919ba64a087365ece03fe2fd9648aac3d09e81e324b41593ddad4aada8121c6c7f020000002fd70736274ff0100df020000000191fcb6f06b5b94586b13101b827bb204d78137d87031a346b27501280b239f0d0000000000539ca180044a0100000000000022002096516bcdab4c23f3fa72953bd7214d1fed2c5b537462593b5e5af212d9c96ea34a01000000000000220020d5d031569d1d9b2697f4e6c58064cae906570a0ca246592abb644b1e070fb28ec309000000000000220020a47089358f15df307dc9fbe6105e8bbaed6f5ec9033307992c5b92f83f75b0b18d7f010000000000220020586919ba64a087365ece03fe2fd9648aac3d09e81e324b41593ddad4aada8121c6c7f0200001012b289a01000000000022002087f8eb092754e219e7a66a6b900360a4cd31b927ed4855469bcbd1268e49b69a220203daa3e7827dcda27b240797ff43691f62ef5db21a3c78da57b33b9c99f280592b47304402204964b53cb5c929857c6c1f5712528ff6ad439ff25221b0c47f6531d81d9966fe02206fcf946f7c330aa0eca026ffaf0c655f7fd3d765f21c6eb278a7ff7c6b3a705d010103040100000001054752210293585196fac8ce82ba42cae3c51deda74667739edf287588cbbe69bf3a07a98d2103daa3e7827dcda27b240797ff43691f62ef5db21a3c78da57b33b9c99f280592b52ae22060293585196fac8ce82ba42cae3c51deda74667739edf287588cbbe69bf3a07a98d084330c3f000000000220603daa3e7827dcda27b240797ff43691f62ef5db21a3c78da57b33b9c99f280592b086c959ddf00000000000101282103daa3e7827dcda27b240797ff43691f62ef5db21a3c78da57b33b9c99f280592bac736460b26800010128210293585196fac8ce82ba42cae3c51deda74667739edf287588cbbe69bf3a07a98dac736460b2680001014d6321037104bcdd022a1507ce3a2e9b975e5b77f2bc82a2217424b9279f26d800278e2e67029000b275210246b6a4612a056a84eb45f00bf490f77aaa4219aaae066bb4a24228e510c48f8c68ac000101252103c9e0ad6900853d166362c7c6a15524c40046f8bd201ea140b247d514fd57d618ad51b2000000000000000000001700000cb14964b53cb5c929857c6c1f5712528ff6ad439ff25221b0c47f6531d81d9966fe6fcf946f7c330aa0eca026ffaf0c655f7fd3d765f21c6eb278a7ff7c6b3a705d010000
```

This indicates that VLS is failing to account for an invoice that was allowlisted before the verifying the commitment. There could be a variety of different causes for this, so we'd want to reproduce this issue using the repro-tester setup similar to what we did with [overflow-panic-repro](https://github.com/Blockstream/greenlight/tree/overflow-panic-repro).

To do so we need the signer logs from someone running on `main`, including the `Processing request` and `Signer state` lines and eventually any line indicating that another state was being used. Using those we can create the JSON representation of the repro case and feed it into the test.

That being said, we have bumped the VLS version a number of times since the case was observed, and we can't reproduce it anymore despite trying several dozen payments, hence why we ask for a repro case in the wild :-)

**Comment by ok300** [comment]
Reproduced here: https://github.com/breez/breez-sdk/issues/481

I also included `trace` logs for `gl_client`, `lightning_signer` and `vls_protocol_signer`.

Let me know if that's enough info to troubleshoot it, or if there's anything else you need.

**Comment by cdecker** [comment]
It appears like that failure stems from the fact that VLS assigns a fixed 10k msat fee to each HTLC, which doesn't match our fee budgeting, so we'll need to relax that limit a bit.

**Comment by cdecker** [comment]
I will remove that debug statement, and if the issue does not reappear I think we can close this, right @ok300?

**Comment by ok300** [comment]
Yes, the issue seems to be gone. This can be closed.
