### ISSUE TITLE
track: Issues starting the signer after signer upgrade

### ISSUE THREAD

**Issue by cdecker** [Blockstream/greenlight#363]
Some users have reported an issue where the signer would be missing a piece of information it was expecting. The signers suddenly expecting a new field suggests that the node had been initialized with a prior version (pre-0.11), opened a channel, and then upgraded the signer to post-0.11.

**Comment by cdecker** [comment]
@devrandom, do you know which field might be the missing one here? I'm looking to find a backtrace that should tell us.

The solution is probably to make the retrieval backfill a default value if not set, or allow continuing without the value for the specific channel in case there is no good default value.

**Comment by devrandom** [comment]
there are no attachments to this issue - which field or code location are affected?

**Comment by cdecker** [comment]
Sadly I have not, but I will keep my eyes open for a sample. In the meantime would it make sense to create a repro test that can take an older version of VLS and then switch to a newer one and see if it can resume normally?

**Comment by devrandom** [comment]
we have a unit test for this, and we have upgraded all of our personal nodes lately.

**Comment by cdecker** [comment]
Perfect, we did deploy v0.11.0-rc.1 for a while which may have temporarily had this regression, we'll make sure to include the signer version should we find another occurrence.
