### ISSUE TITLE
Warning when starting a node: `warning_lightningd_sync: "Still loading latest blocks from bitcoind"` 

### ISSUE THREAD

**Issue by ilearnio** [Blockstream/greenlight#392]
I'm trying to setup GleenLight by following the instructions here https://blockstream.github.io/greenlight/getting-started/schedule/, but I keep getting this warning when I am starting the node (using python script). It's there for more than a week already.

```
warning_lightningd_sync: "Still loading latest blocks from bitcoind."
```

![image](https://github.com/Blockstream/greenlight/assets/14331216/bb0a49fd-e35d-4506-8d7e-4bc7617885d7)

Here's my node-start.py which results into an error:

```py
from glclient import TlsConfig, Scheduler, Signer, clnpb

# Read seed from seed-secret.bin
with open('seed-secret.bin', 'rb') as f:
  seed = f.read()

# Read cert
with open('client.crt', 'r') as f:
  cert = f.read()

# Read key
with open('client-key.pem', 'r') as f:
  key = f.read()

# Creating a new `TlsConfig` object using your developer certificate
tls = TlsConfig().identity(cert, key)

signer = Signer(seed, network="bitcoin", tls=tls)
signer.run_in_thread()

# Read cert
with open('device-cert.crt', 'r') as f:
  cert = f.read()

# Read key
with open('device-key.pem', 'r') as f:
  key = f.read()

node_id = signer.node_id()
network = "bitcoin"
tls = TlsConfig().identity(cert, key)

scheduler = Scheduler(node_id, network, tls)
node = scheduler.node()


info = node.get_info()
peers = node.list_peers()

print(info)
print("peers:")
print(peers)


invoice = node.invoice(
    amount_msat=clnpb.AmountOrAny(any=True),
    label="label",
    description="description",
)

print("invoice:")
print(invoice)
```

Also, the process is hanging indefinitely at this line `invoice = node.invoice(`, not sure if that's intended

**Comment by ErikDeSmedt** [comment]
I'm currently working to reproduce the issue.

- Are you using `glclient` from the `main`-branch or did you install from `PyPI`?
- Are you sure you registered your node on `bitcoin` and not on `testnet`?

**Comment by ErikDeSmedt** [comment]
You can use the `device`-certificate for both the signer and the node.
Could you try again with the following script?

``` python
from glclient import TlsConfig, Scheduler, Signer, clnpb

# Read seed from seed-secret.bin
with open('seed-secret.bin', 'rb') as f:
  seed = f.read()

# Read cert
with open('device-cert.crt', 'r') as f:
  cert = f.read()

# Read key
with open('device-key.pem', 'r') as f:
  key = f.read()

# Creating a new `TlsConfig` object using your developer certificate
tls = TlsConfig().identity(cert, key)

signer = Signer(seed, network="bitcoin", tls=tls)
signer.run_in_thread()

node_id = signer.node_id()
network = "bitcoin"
tls = TlsConfig().identity(cert, key)

scheduler = Scheduler(node_id, network, tls)
node = scheduler.node()


info = node.get_info()
peers = node.list_peers()

print(info)
print("peers:")
print(peers)


invoice = node.invoice(
    amount_msat=clnpb.AmountOrAny(any=True),
    label="some-label",
    description="description",
)

print("invoice:")
print(invoice)
```

**Comment by ilearnio** [comment]
Thanks @ErikDeSmedt. That seems to fix the hanging issue

![image](https://github.com/Blockstream/greenlight/assets/14331216/41dc3faa-93b3-466a-9594-75862cb50076)

However its still showing this:
```
warning_lightningd_sync: "Still loading latest blocks from bitcoind."
```

**Comment by cdecker** [comment]
Hi @ilearnio :wave: 

The warning is normal and nothing to be concerned about. The nodes on Greenlight are started on demand, and, while we do start the nodes in the background to let them sync up with the blockchain, chances are that at the next time the user comes back there will almost always have been a new block, meaning the node is syncing again, and printing this warning. The warnign goes away after some minutes of running, and will reappear the next time the node is started.

As for the hanging issue, that is usually because you have issued a command requiring a signature (`invoice` signs the invocie with the node_id) and there is no signer currently connected. We are seeing a bit of flakiness in signer connections, which may also cause sporadic missing signers, but we are working on a fix for that too.
