### ISSUE TITLE
Generic connection error

### ISSUE THREAD

**Issue by fossephate** [Blockstream/greenlight#422]
Implementing via breez I get:
```
Error connecting to Breez: FrbAnyhowException(Generic: Generic: transport error)
```

![image](https://github.com/Blockstream/greenlight/assets/6175367/bd170875-b149-45d7-b494-96e394865fb9)
![image](https://github.com/Blockstream/greenlight/assets/6175367/a8018aeb-c38f-49b2-b857-7eab0d9b9766)
![image](https://github.com/Blockstream/greenlight/assets/6175367/5dc9f7a4-1133-47c5-b4a1-4a389cd7a20a)

**Comment by kingonly** [comment]
@cdecker "transport error" while connecting to a node
@fossephate please share the node id

**Comment by fossephate** [comment]
node id? I'm not sure what you're referring to

**Comment by dangeross** [comment]
@fossephate Do you have any existing log files from previously connecting?

If you are able to connect:
- You can use in flutter `sdk.nodeInfo()` to get the NodeState which contains the id.  
- You can use from 0.3.9 `sdk.generateDiagnosticData()` to fetch a set of GL/SDK diagnostic data that we can use the diagnose issues with

**Comment by fossephate** [comment]
trying to call `generateDiagnosticData()` I get:
FrbAnyhowException(Generic: Node service was not initialized)

![image](https://github.com/Blockstream/greenlight/assets/6175367/ffc70a62-d8be-4d68-8aed-6a375af9e3e4)

**Comment by dangeross** [comment]
This can also only be called if the SDK connects successfully

**Comment by cdecker** [comment]
This is likely tracked by #428 where we track the `transport error` for `gl-client`. Can we close this as duplicate? (I know opening a new issue and marking the original one as duplicate is a bit strange but #428 contains more context)

**Comment by fossephate** [comment]
sorry I forgot to update this, it turned out to just be an issue with how I was passing the credentials (I wasn't base64 encoding the whole file, just passing the base64 encoded part)
