### ISSUE TITLE
Relai: Sweep tx is not executed

### ISSUE THREAD

**Issue by roeierez** [Blockstream/greenlight#426]
NodeID:  2a15ccf252e2cf16a0c34112b9d3edefefbd8f72f961ea97f7b38d3a5592fda5
User has a closed channel with some htlcs. Closing tx: https://blockstream.info/tx/6a358b396d127e1f5eea12f2f49114ea6934ab95d8355ab842b027c0cae3cc4a

The user's outputs are not swept and the payment that caused the channel closure is still pending.

issue: https://github.com/breez/breez-sdk-relai/issues/27

**Comment by JordiZDG** [comment]
Is there any update I can tell the user?

**Comment by ErikDeSmedt** [comment]
This appears to be the same issue as https://github.com/Blockstream/greenlight/issues/439

**Comment by cdecker** [comment]
Quickly relaying the discussion from the private trackers (to keep the user's information away from the public):

We have found that for the closing transaction there are 6 outputs that have not been swept so far. Looking into the logs we found that the node is still trying to sweep those funds, but does not have enough funds to fee-bump the transaction through the anchor outputs.

The solution here is to either add more funds to the node (probably not what the user wants to do at the moment), or we need to wait until the fees get low enough again for the existing sweep transactions to work.

**Comment by JordiZDG** [comment]
> The solution here is to either add more funds to the node 

@cdecker  , can I add more funds to the node via an on-chain transaction from my wallet to unlock the user's funds? If yes, to which address should I send the sats (I was thinking about €5-10)?

**Comment by cdecker** [comment]
That could be one option, yes. I'm a bit hesitant to throw more funds at a stuck node as it's unlikely to be an option for other occurrences. If you want to try, you can get an on-chain address with the `NewAddr()` method in gl-client, and I'm positive the Breez SDK also wires it through somehow.
