### ISSUE TITLE
track: commitment transaction desync VLS <> CLN

### ISSUE THREAD

**Issue by cdecker** [Blockstream/greenlight#431]
This is a tracking issue for the root cause of a number of issues,
listed at the bottom. The issue at hand is that up until [#7027][7027]
we had an issue that could result in the signer state being updated,
but the CLN state not reflecting that change. With [#7027][7027] this
issue has been resolved, however nodes that were in this situation
cannot back out of it, as that would equate to a replay of an old
state, and the validation is there to explicitly prevent that.

If VLS were to implement a mode (as a `SimpleValidatorFactory`
argument?) that tells VLS to temporarily opt out of the enforcement of
this policy, we could use that to get the nodes unstuck, close the
channel, and get back to a situation where the VLS and the CLN state
match up again. 

Discussing this with @ksedgwic, the signer will always sign based on
its local state, and so the options are two:

 - Patch the state before invoking: this is essentially overwriting
   the signer state with whatever the node is reporting back, ensuring
   that the local state and the state provided by the request match
   up. This would mean that the special permissive mode doesn't have
   to be wired through the call-stack, but involves introspecting the
   state in two places (the patching side and the processing side).
 - Wire the special mode through to the verification, and base
   descisions on the request transaction, rather than the local state
   transaction. This would involve more code changes as both have to
   be handed down the call-stack, as well as a flag to signal which
   state to use for signing, but most of that is already passed down
   for verification of equality anyway.
   
The VLS team will likely know which variant (a) fits better with their
general architecture, and (b) cause the least amount of disturbance
for what is after all a relatively rare occasion (that could manifest
in different ways in the future, so a clean architecture and
extensibility is desirable here to get users unstuck).

## Related issues

 - https://github.com/Blockstream/greenlight/issues/420
 - https://github.com/Blockstream/greenlight/issues/349

[7027]: https://github.com/ElementsProject/lightning/pull/7027

**Comment by cdecker** [comment]
Known instances:

 - [ ] `02aff1834ae45d42bcf9e2eb6994d52db2673ea5b09f48100aa73b255851972f5c`
 - [ ]

**Comment by cdecker** [comment]
We have a patch merged into VLS: https://gitlab.com/lightning-signer/validating-lightning-signer/-/merge_requests/686

We expect that this patch prevents CLN and VLS from desynching due to a repeated `revoke_previous_holder_commitment`. This is due to a replay of a potentially unacknowledged revocation after restart.

**Comment by roeierez** [comment]
@cdecker  That sounds like good news. I am guessing we should follow up here with a breez sdk release. Will it be on top of greenlight main or you prefer to hotfix the latest stable of greenlight with this VLS patch (The one that the sdk was released from)?

**Comment by cdecker** [comment]
There are quite a few changes that we'll need to check before catching up with VLS, and then the SDK can pull in from `main`. We'll leave this PR open until then.

**Comment by cdecker** [comment]
With the publication of the latest version we can consider this one as closed.
