### ISSUE TITLE
Relai: Weird sweep behavior after closed channel

### ISSUE THREAD

**Issue by roeierez** [Blockstream/greenlight#432]
After channel was forced closed by remote, there is a weird behavior where:
1. some of the outputs are swept, some not event though they were sent to the same address
2. some of the closing tx output is included in the wallet utxos and part of the onchain balance.

Explained in details here: https://github.com/breez/breez-sdk-relai/issues/40

**Comment by cdecker** [comment]
This is an occurrence of #439, marking as duplicate and waiting for upstream fix (which might also be me, but everything in its place).

```
billboard: 3 outputs unresolved: in 4294963866 blocks will spend OUR_HTLC (a792ab6799ac5ab9100091ea7010c0cb18780a7697ab17d4e45d433dedc07a0b:2) using OUR_HTLC_TIMEOUT_TO_US
```
