### ISSUE TITLE
Relai: User can't create invoice

### ISSUE THREAD

**Issue by roeierez** [Blockstream/greenlight#435]
NodeID: 02fcc5bfc48e83f06c04483a2985e1c390cb0f35058baa875ad2053858b8e80dbd

https://github.com/breez/breez-sdk-relai/issues/9

**Comment by cdecker** [comment]
After debugging this further we see that it is an instance of https://github.com/Blockstream/greenlight/issues/431, closing as a duplicate, we'll continue tracking it internally too :+1:

**Comment by JordiZDG** [comment]
What can I say to the user?
