### ISSUE TITLE
Part of the balance is missing

### ISSUE THREAD

**Issue by JordiZDG** [Blockstream/greenlight#440]
User: bc1q8h6st0phkv56uutjsksu3yzwfa92f6p0m82a2m

> "Hello, my account balance on the Lightning Wallet does not show the correct balance. The balance of BTC has decreased instead of increased after receiving BTC.
> It was previously 0.00085669 and after receiving 0.0001771 it is now only 0.00017710 BTC.
> The rest 0.00085669 (what I had before) has somehow disappeared?!
> Please help"

Diagnostic: 
[diagnostic_data_bc1q8h6st0phkv56uutjsksu3yzwfa92f6p0m82a2m.log](https://github.com/Blockstream/greenlight/files/15298383/diagnostic_data_bc1q8h6st0phkv56uutjsksu3yzwfa92f6p0m82a2m.log)

**Comment by cdecker** [comment]
Has this been cleared with the user? I can look up what happened with funds on the node if the user hasn't gotten them back yet. It sounds like a channel was closed and temporarily not counted towards our funds.

**Comment by JordiZDG** [comment]
I was wrong to open the issue here. I then uploaded it [here ](https://github.com/breez/breez-sdk-relai/issues/46)and it has now been resolved.
