### ISSUE TITLE
"Bitcoin" network when "Testnet" parameter used

### ISSUE THREAD

**Issue by evd0kim** [Blockstream/greenlight#441]
I noticed that my simple script (built using snippets on the documentation website) leads to "bitcoin" network get info, whereas the "testnet" argument is used in Signer and Scheduler.

I'm not sure if the node was initialized as "Bitcoin," but it should lead to an error message or exception anyway.

**Comment by ErikDeSmedt** [comment]
I think this issue is fixed in https://github.com/Blockstream/greenlight/pull/376/commits/9a081073eabc036681dacc49bc5465f9aa913b3d. However, we haven't released the code yet.

@Randy808 : Can you confirm this MR is a fix for the issue?

**Comment by evd0kim** [comment]
> Yes, it was mostly there as redundant information, and not used anywhere.

Okay, thanks. I had a clue about that. I could indeed missed 'bitcoin' when registering new instance.
