### ISSUE TITLE
Channel closed with weird htlc state

### ISSUE THREAD

**Issue by roeierez** [Blockstream/greenlight#446]
Relai: https://github.com/breez/breez-sdk-relai/issues/36

Channel was forced closed by the user node. Delayed output was swept 10 blocks after the closing tx which perhaps means that the other side has swept?
A bit of confusing case, appreciate your help.
Bottom line user had 149992 sats in the balance, channel was closed and funds looks like swept but not by the user's node.

**Comment by JordiZDG** [comment]
Any update?

**Comment by roeierez** [comment]
@cdecker here is some more info: https://github.com/breez/breez-sdk-relai/issues/36#issuecomment-2123374147

**Comment by cdecker** [comment]
The related issue has been closed, as the sweeps appear to have gone through or are still being monitored. Closing this to match.
