### ISSUE TITLE
Upgrade to master crashes node.

### ISSUE THREAD

**Issue by roeierez** [Blockstream/greenlight#464]
On first run when upgrading to master the node crashes.
Seems like it is a result of signer upgrade.

**Comment by cdecker** [comment]
From what I can tell this is related to `maybe_upgrade` not completing before the node gets scheduled, causing the old version to be started, which doesn't match with the signer version, which then causes the crash. I'll dig into this further

**Comment by roeierez** [comment]
Thanks. Perhaps also worth also stopping the node right after maybe_upgrade (in case of real upgrade) because the node can be online at that time.

**Comment by cdecker** [comment]
Yep, that's the plan. Actually stopping would already be sufficient as it'd be immediately rescheduled by the client connecting 👍

**Comment by cdecker** [comment]
This has been merged and will be deployed on the server side tomorrow 👍

**Comment by cdecker** [comment]
Confirmed that this is no longer an issue.
