### ISSUE TITLE
Bad gossip order: could not find channel *** for peer's channel update

### ISSUE THREAD

**Issue by danielgranhao** [Blockstream/greenlight#507]
On a specific node of ours (a rather new one) we started having trouble making payments. It seems many payment attempts fails due to `WIRE_UNKNOWN_NEXT_PEER`.

We also see a lot (~5000) of these logged errors:
```
2024-08-29T04:35:46.846804Z [INFO] node-logs: UNUSUAL lightningd: Bad gossip order: could not find channel 841229x2257x0 for peer's channel update
```

The affected node's id is `03f7116e75ab5755e3ac9a24dc4ce3967bac541384eee4f547781e30a49fc28f2b `.

**Comment by JssDWt** [comment]
It appears the UNKNOWN_NEXT_PEER errors are because it's trying to pay to WOS over a channel that no longer exists.

**Comment by cdecker** [comment]
The gossip warnings are innocuous, so let's concentrate on the unknown next peer error. We found an issue yesterday that could resurface zombie channels in our router, causing these attempts to use no longer available channels. We'll deploy the fix today.
