### ISSUE TITLE
[Breez] Failure to connect to SDK

### ISSUE THREAD

**Issue by DeanDonkov** [Blockstream/greenlight#510]
We, a customer of the Breez platform seem to be experiencing connection issues to GL's nodes.

`[Error: Generic: status: Unavailable, message: "error trying to connect: received fatal alert: Unknown(225)", details: [], metadata: MetadataMap { headers: {} }]
`

Attaching the [SDK logs](https://github.com/user-attachments/files/16863522/breez-sdk-log.txt) which show logs for the lifecycle of the connect method of Breez SDK.

From the logs, this is seemingly an indication that the connection stream got ended.

```
2024-09-04T08:43:00.854Z - {
  "line": "recv HEADERS frame=Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }",
  "level": "TRACE"
}
```

**Comment by DeanDonkov** [comment]
Update: It has been fixed for now.

**Comment by cdecker** [comment]
As you can see in the docs I recently (I think after your initial report) published the error code 225 corresponds to an internal server-side error. These are for our ops team to fix, and we try to keep them minimal, but sometimes the users may see them. In this case it was a DB connection pool running over. Apologies for the inconvenience and thanks for reporting this.

**Comment by cdecker** [comment]
Of course if I were to add a link to the previous comment it'd be more useful: https://blockstream.github.io/greenlight/reference/node-domain/ 😅
