### ISSUE TITLE
Generic: status: Unavailable, message: "error trying to connect: received fatal alert: Unknown(223)

### ISSUE THREAD

**Issue by neveero** [Blockstream/greenlight#517]
Receiving the below error when trying to restore a specific seed via Breez SDK:

```
java.lang.Exception: breez_sdk.ConnectException$Generic: Generic: status: Unavailable, message: "error trying to connect: received fatal alert: Unknown(223)", details: [], metadata: MetadataMap { headers: {} }
```

Any ideas on what I can try please?

**Comment by cdecker** [comment]
This is a server-side error: the node-domain proxy was unable to talk to the scheduler to get the location of the node. This has been addressed on the service, and should not reappear now.
