### ISSUE TITLE
Wrap `send_pay` in awaitable channel futures

### ISSUE THREAD

**Issue by JssDWt** [Blockstream/greenlight#522]
It would be great if `send_pay` could be wrapped in awaitable channel futures, just like `pay` and `trampoline_pay`. The Breez SDK uses `send_pay` to pay for reverse swaps. They sometimes fail with `failed: WIRE_TEMPORARY_CHANNEL_FAILURE (First peer not ready)`, meaning the channels between greenlight and the LSP are not yet reestablished at the moment of calling `send_pay`.

**Comment by cdecker** [comment]
We have this patch pending deployment, but are fighting with the CI to get them deployed. I'll update here once the patches are deployed.

**Comment by cdecker** [comment]
This patch has been deployed last week :+1:
