### ISSUE TITLE
Add ability to query for closed channels

### ISSUE THREAD

**Issue by roeierez** [Blockstream/greenlight#70]
Currently at some point the close channel is "forgotten".
Would be great to have an option not do "forget" these channels and have the ability to fetch them.

We also want to show the user some info about the closed channel such as:
1. Closing tx id
2. The timeout expiration height (On which block height our side of the channel can be swept on-chain).

**Comment by cdecker** [comment]
`listclosedchannels` has been deployed and tested on `prod` :-)
